%YAML 1.2
---
name: product_chatbot
comment: Provide information about product
model:
    # id: text-davinci-003
    id: gpt-3.5-turbo
    # id: claude-v1
prompt:
    - template: product_prompt.jinja
    - template: product_info_prompt.jinja
