%YAML 1.2
---
name: Youtube Title Generator
comment: An agent to generate youtube titles
model:
    # id: text-davinci-003
    id: gpt-3.5-turbo
    # id: claude-v1
prompt:
    - template: title_template.jinja