%YAML 1.2
---
name: Youtube Title and Script Generator
comment: An agent to generate youtube titles and scripts
model:
    # id: text-davinci-003
    id: gpt-3.5-turbo
    # id: claude-v1
prompt:
    - template: title_template.jinja
    - template: script_template.jinja